### ISSUE TITLE
No explicit license for this repo present

### ISSUE THREAD

**Issue by grossws** [hyperhq/runv#165]

**Comment by laijs** [comment]
Thanks for report, this repo is originated from hyper, the license of hyper is https://github.com/hyperhq/hyper/blob/master/LICENSE.

we might also copy the license here.

**Comment by bpradipt** [comment]
@laijs it will be good to add the license file to runv project as well. Makes it clear and unambiguous. 
Thanks

**Comment by laijs** [comment]
fixed by #179
