### ISSUE TITLE
Runv does not run on powerpc as it can not find exec whose seq is 1 from hyper_win_size.

### ISSUE THREAD

**Issue by abdasgupta** [hyperhq/runv#169]
Below is the log:

hyper_handle_event get event 16, de 0x100311dc338, fd 11. ops 0x10025950^M
hyper_handle_event event EPOLLHUP, de 0x100311dc338, fd 11, 0x10025950^M
stdin_hup^M
pts_hup, seq 1^M
last user of exec exit, release^M
hyper_modify_event modify event fd 4, 0x10025d88, event 5^M
hyper_release_exec exit code 255^M
hyper_release_exec container init exited, type 17, remains 1, policy 0^M
hyper send type 13, len 4^M
fopen /proc/324/status^M
find sigign     0000000000000000^M
mask is 0^M
open /tmp/hyper/resolv.conf failed: No such file or directory^M
hyper_loop epoll_wait 1^M
hyper_handle_event get event 4, de 0x10025d88, fd 4. ops 0x10025920^M
hyper_handle_event event EPOLLOUT, de 0x10025d88, fd 4, 0x10025920^M
hyper_modify_event modify event fd 4, 0x10025d88, event 1^M
hyper_loop epoll_wait 1^M
hyper_handle_event get event 1, de 0x10025dc0, fd 3. ops 0x100258f0^M
hyper_handle_event event EPOLLIN, de 0x10025dc0, fd 3, 0x100258f0^M
hyper_event_read^M
already read 8 bytes data^M
hyper send type 14, len 4^M
get length 39^M
read 31 bytes data, total data 39^M
hyper send type 14, len 4^M
0 0 0 b 0 0 0 27 7b 22 63 6f 6c 75 6d 6e 22 3a 31 36 39 2c 22 72 6f 77 22 3a 34 37 2c 22 73 65 71 22 3a 31 7d ^M
 hyper_channel_handle, type 11, len 39^M
call hyper_win_size, json {"column":169,"row":47,"seq":1}41df0708ae52382d350a8d9a936ac2d22ff6e16f","rootfs":"rootfs","image":"8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f","process":{"terminal":true,"stdio":1,"args":["sh"],"envs":[{"env":"PATH","value":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},{"env":"TERM","value":"xterm"}],"workdir":"/"},"restartPolicy":"never","initialize":false}, len 31^M
can not find exec whose seq is 1^M
hyper send type 9, len 0^M
hyper_loop epoll_wait 1^M
hyper_handle_event get event 1, de 0x10025dc0, fd 3. ops 0x100258f0^M
hyper_handle_event event EPOLLIN, de 0x10025dc0, fd 3, 0x100258f0^M
hyper_event_read^M
already read 8 bytes data^M
hyper send type 14, len 4^M
get length 8^M
0 0 0 4 0 0 0 8 ^M
 hyper_channel_handle, type 4, len 8^M
get DESTROYPOD message^M
hyper send type 9, len 0^M
reboot: Power down^M
RTAS power-off r

Any idea??

**Comment by gao-feng** [comment]
It doesn't matter with winsize. The container init process 'sh' whose seq is 1,
you can get the log that 
`hyper_release_exec exit code 255^M
hyper_release_exec container init exited, type 17, remains 1, policy 0^M
`, 
it means the 'sh' met some problems and exited with code 255. can you post
the whole log, the config.json  and runtime.json?

**Comment by abdasgupta** [comment]
I am attaching the log file that is generated from inside the VM after it is spawned by qemu:



SLOF[0m[?25l **********************************************************************
[1mQEMU Starting
[0m Build Date = Mar 18 2015 18:46:54
 FW Version = mockbuild@ release 20150313
 Press "s" to enter Open Firmware.



[0m[?25hC0000C0100C0120C0140C0200C0201C0220C0240C0260C0270C02E0C0300C0320C0340C0360C0370C0380C0371C0372C0373C0374C0390C03F0C0400C0480C04C0C04D0C0500Populating /vdevice methods
Populating /vdevice/vty@71000000
Populating /vdevice/nvram@71000001
C0580C05A0Populating /pci@800000020000000

 Adapters on 0800000020000000
                     00 0000 (D) : 1af4 1009    virtio [ network ]
Populating /pci@800000020000000/unknown-legacy-device@0
                     00 1000 (D) : 1af4 1003    communication-controller*
                     00 1800 (D) : 1af4 1004    virtio [ scsi ]
Populating /pci@800000020000000/scsi@3
       SCSI: Looking for devices
C0600C0640C0690C06A0C06A8C06B0C06B8C06C0C06E0C0700C0800C0880No NVRAM common partition, re-initializing...
C0890C08A0C08A8C08B0Scanning USB 
C08C0C08D0Using default console: /vdevice/vty@71000000
C08E0C08E8Detected RAM kernel at 400000 (111e164 bytes) C08FF     
  Welcome to Open Firmware

  Copyright (c) 2004, 2011 IBM Corporation All rights reserved.
  This program and the accompanying materials are made available
  under the terms of the BSD License available at
  http://www.opensource.org/licenses/bsd-license.php

Booting from memory...
OF stdout device is: /vdevice/vty@71000000
Preparing to boot Linux version 4.6.0-rc2 (bpradipt@moby) (gcc version 5.3.1 20160330 (Ubuntu/IBM 5.3.1-13ubuntu3) ) #3 SMP Wed Apr 6 08:07:55 CDT 2016
Detected machine type: 0000000000000101
Max number of cores passed to firmware: 32 (NR_CPUS = 32)
Calling ibm,client-architecture-support... done
command line: 
memory layout at init:
  memory_limit : 0000000000000000 (16 MB aligned)
  alloc_bottom : 0000000001523000
  alloc_top    : 0000000010000000
  alloc_top_hi : 0000000010000000
  rmo_top      : 0000000010000000
  ram_top      : 0000000010000000
instantiating rtas at 0x000000000ffff000... done
prom_hold_cpus: skipped
copying OF device tree...
Building dt strings...
Building dt structure...
Device tree strings 0x0000000001724000 -> 0x00000000017248c4
Device tree struct  0x0000000001725000 -> 0x0000000001728000
Quiescing Open Firmware ...
Booting Linux via __start() ...
 -> fw_cmo_feature_init()
CMO not available
 <- fw_cmo_feature_init()
 <- pSeries_init_early()
CPU maps initialized for 1 thread per core
 (thread shift is 0)
Freed 28672 bytes for unused pacas
 -> smp_release_cpus()
spinning_secondaries = 0
 <- smp_release_cpus()
Starting Linux ppc64le #3 SMP Wed Apr 6 08:07:55 CDT 2016
-----------------------------------------------------
ppc64_pft_size    = 0x15
phys_mem_size     = 0x10000000
cpu_features      = 0x37fc7a6c18500249
  possible        = 0x3fffffff18500649
  always          = 0x0000000018100040
cpu_user_features = 0xdc0065c2 0xef000000
mmu_features      = 0x58000001
firmware_features = 0x000000014052440b
htab_hash_mask    = 0x3fff
-----------------------------------------------------
 <- setup_system()
Linux version 4.6.0-rc2 (bpradipt@moby) (gcc version 5.3.1 20160330 (Ubuntu/IBM 5.3.1-13ubuntu3) ) #3 SMP Wed Apr 6 08:07:55 CDT 2016
Node 0 Memory: 0x0-0x10000000
numa: Initmem setup node 0 [mem 0x00000000-0x0fffffff]
numa:   NODE_DATA [mem 0x0ffc1b00-0x0ffcbfff]
 -> smp_init_pSeries()
 <- smp_init_pSeries()
PCI host bridge /pci@800000020000000  ranges:
  IO 0x0000010080000000..0x000001008000ffff -> 0x0000000000000000
 MEM 0x00000100a0000000..0x000001101fffffff -> 0x0000000080000000 
PPC64 nvram contains 65536 bytes
Top of RAM: 0x10000000, Total RAM: 0x10000000
Memory hole size: 0MB
Zone ranges:
  DMA      [mem 0x0000000000000000-0x000000000fffffff]
  DMA32    empty
  Normal   empty
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x0000000000000000-0x000000000fffffff]
Initmem setup node 0 [mem 0x0000000000000000-0x000000000fffffff]
On node 0 totalpages: 65536
  DMA zone: 896 pages used for memmap
  DMA zone: 0 pages reserved
  DMA zone: 65536 pages, LIFO batch:15
percpu: Embedded 27 pages/cpu @c00000000ffa6000 s70680 r0 d39912 u110592
pcpu-alloc: s70680 r0 d39912 u110592 alloc=27*4096
pcpu-alloc: [0] 0 
Built 1 zonelists in Node order, mobility grouping on.  Total pages: 64640
Policy zone: DMA
Kernel command line: 
PID hash table entries: 1024 (order: 1, 8192 bytes)
Sorting __ex_table...
Memory: 238768K/262144K available (9544K kernel code, 956K rwdata, 2744K rodata, 2528K init, 1724K bss, 23376K reserved, 0K cma-reserved)
SLUB: HWalign=128, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
Hierarchical RCU implementation.
	Build-time adjustment of leaf fanout to 64.
	RCU restricting CPUs from NR_CPUS=32 to nr_cpu_ids=1.
RCU: Adjusting geometry for rcu_fanout_leaf=64, nr_cpu_ids=1
NR_IRQS:512 nr_irqs:512 16
pic: no ISA interrupt controller
time_init: decrementer frequency = 512.000000 MHz
time_init: processor frequency   = 3425.000000 MHz
clocksource: timebase: mask: 0xffffffffffffffff max_cycles: 0x761537d007, max_idle_ns: 440795202126 ns
clocksource: timebase mult[1f40000] shift[24] registered
clockevent: decrementer mult[83126e98] shift[32] cpu[0]
Console: colour dummy device 80x25
console [hvc0] enabled
console [hvc0] enabled
bootconsole [udbg0] disabled
bootconsole [udbg0] disabled
pid_max: default: 32768 minimum: 301
Dentry cache hash table entries: 32768 (order: 6, 262144 bytes)
Inode-cache hash table entries: 16384 (order: 5, 131072 bytes)
Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
EEH: pSeries platform initialized
POWER8 performance monitor hardware support registered
power8-pmu: PMAO restore workaround active.
Brought up 1 CPUs
Node 0 CPUs: 0
devtmpfs: initialized
EEH: devices created
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
NET: Registered protocol family 16
EEH: No capable adapters found
IBM eBus Device Driver
cpuidle: using governor menu

Linux ppc64le
#3 SMP Wed Apr 6rtas_msi: Registering RTAS MSI callbacks.
PCI: Probing PCI hardware
no ibm,pcie-link-speed-stats property
PCI host bridge to bus 0000:00
pci_bus 0000:00: root bus resource [io  0x10000-0x1ffff] (bus address [0x0000-0xffff])
pci_bus 0000:00: root bus resource [mem 0x100a0000000-0x1101fffffff] (bus address [0x80000000-0xfffffffff])
pci_bus 0000:00: root bus resource [bus 00-ff]
pci_dma_bus_setup_pSeriesLP: setting up bus /pci@800000020000000
  parent is /pci@800000020000000, iommu_table: 0x          (null)
IOMMU table initialized, virtual merging enabled
  created table: c00000000e030c00
pci_dma_dev_setup_pSeriesLP: 0000:00:00.0
  node is /pci@800000020000000/unknown-legacy-device@0
  parent is /pci@800000020000000
  found DMA window, table: c00000000e030c00
rtas_msi: No ibm,req#msi on /pci@800000020000000/unknown-legacy-device@0
pci 0000:00:00.0: rtas_msi: disabling existing MSI.
rtas_msi: ibm,change_msi(func=3,num=0), got 0 rc = -1
rtas_msi: ibm,change_msi(func=1,num=0), got 0 rc = -1
rtas_msi: Setting MSIs to 0 failed!
pci_dma_dev_setup_pSeriesLP: 0000:00:02.0
  node is /pci@800000020000000/communication-controller@2
  parent is /pci@800000020000000
  found DMA window, table: c00000000e030c00
rtas_msi: No ibm,req#msi on /pci@800000020000000/communication-controller@2
pci 0000:00:02.0: rtas_msi: disabling existing MSI.
rtas_msi: ibm,change_msi(func=3,num=0), got 0 rc = -1
rtas_msi: ibm,change_msi(func=1,num=0), got 0 rc = -1
rtas_msi: Setting MSIs to 0 failed!
pci_dma_dev_setup_pSeriesLP: 0000:00:03.0
  node is /pci@800000020000000/scsi@3
  parent is /pci@800000020000000
  found DMA window, table: c00000000e030c00
rtas_msi: No ibm,req#msi on /pci@800000020000000/scsi@3
pci 0000:00:03.0: rtas_msi: disabling existing MSI.
rtas_msi: ibm,change_msi(func=3,num=0), got 0 rc = -1
rtas_msi: ibm,change_msi(func=1,num=0), got 0 rc = -1
rtas_msi: Setting MSIs to 0 failed!
PCI: Probing PCI hardware done
vgaarb: loaded
SCSI subsystem initialized
libata version 3.00 loaded.
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
pps_core: LinuxPPS API ver. 1 registered
pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
PTP clock support registered
EDAC MC: Ver: 3.0.0
clocksource: Switched to clocksource timebase
hugetlbfs: disabling because there are no supported hugepage sizes
NET: Registered protocol family 2
TCP established hash table entries: 2048 (order: 2, 16384 bytes)
TCP bind hash table entries: 2048 (order: 3, 32768 bytes)
TCP: Hash tables configured (established 2048 bind 2048)
UDP hash table entries: 256 (order: 1, 8192 bytes)
UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
PCI: CLS 0 bytes, default 128
Trying to unpack rootfs image as initramfs...
Freeing initrd memory: 1880K (c000000001530000 - c000000001706000)
rtasd: No event-scan on system
Hypercall H_BEST_ENERGY not supported
futex hash table entries: 256 (order: 3, 32768 bytes)
workingset: timestamp_bits=52 max_order=16 bucket_order=0
NFS: Registering the id_resolver key type
Key type id_resolver registered
Key type id_legacy registered
9p: Installing v9fs 9p2000 file system support
cryptomgr_test (32) used greatest stack depth: 14416 bytes left
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
io scheduler noop registered
io scheduler deadline registered
io scheduler cfq registered (default)
pci_hotplug: PCI Hot Plug PCI Core version: 0.5
virtio-pci 0000:00:00.0: enabling device (0100 -> 0103)
virtio-pci 0000:00:00.0: virtio_pci: leaving for legacy driver
virtio-pci 0000:00:00.0: node is /pci@800000020000000/unknown-legacy-device@0
virtio-pci 0000:00:02.0: enabling device (0100 -> 0103)
virtio-pci 0000:00:02.0: virtio_pci: leaving for legacy driver
virtio-pci 0000:00:02.0: node is /pci@800000020000000/communication-controller@2
virtio-pci 0000:00:03.0: enabling device (0100 -> 0103)
virtio-pci 0000:00:03.0: virtio_pci: leaving for legacy driver
virtio-pci 0000:00:03.0: node is /pci@800000020000000/scsi@3
Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
rtas_msi: calc quota for 0000:00:02.0, request 2
rtas_msi: found prop on dn /pci@800000020000000
rtas_msi: found PE /pci@800000020000000
rtas_msi: counting /pci@800000020000000/unknown-legacy-device@0
rtas_msi: counting /pci@800000020000000/communication-controller@2
rtas_msi: counting /pci@800000020000000/scsi@3
rtas_msi: calc quota for 0000:00:02.0, request 2
rtas_msi: found prop on dn /pci@800000020000000
rtas_msi: found PE /pci@800000020000000
rtas_msi: counting /pci@800000020000000/unknown-legacy-device@0
rtas_msi: counting /pci@800000020000000/communication-controller@2
rtas_msi: counting /pci@800000020000000/scsi@3
rtas_msi: ibm,change_msi(func=4,num=2), got 2 rc = 2
virtio-pci 0000:00:02.0: rtas_msi: allocated virq 23
virtio-pci 0000:00:02.0: rtas_msi: allocated virq 24
brd: module loaded
loop: module loaded
Uniform Multi-Platform E-IDE driver
ide-gd driver 1.18
ide-cd driver 5.00
ipr: IBM Power RAID SCSI Device Driver version: 2.6.3 (October 17, 2015)
rtas_msi: calc quota for 0000:00:03.0, request 4
rtas_msi: found prop on dn /pci@800000020000000
rtas_msi: found PE /pci@800000020000000
rtas_msi: counting /pci@800000020000000/unknown-legacy-device@0
rtas_msi: counting /pci@800000020000000/communication-controller@2
rtas_msi: counting /pci@800000020000000/scsi@3
rtas_msi: calc quota for 0000:00:03.0, request 4
rtas_msi: found prop on dn /pci@800000020000000
rtas_msi: found PE /pci@800000020000000
rtas_msi: counting /pci@800000020000000/unknown-legacy-device@0
rtas_msi: counting /pci@800000020000000/communication-controller@2
rtas_msi: counting /pci@800000020000000/scsi@3
rtas_msi: ibm,change_msi(func=4,num=4), got 4 rc = 4
virtio-pci 0000:00:03.0: rtas_msi: allocated virq 25
virtio-pci 0000:00:03.0: rtas_msi: allocated virq 26
virtio-pci 0000:00:03.0: rtas_msi: allocated virq 27
virtio-pci 0000:00:03.0: rtas_msi: allocated virq 28
scsi host0: Virtio SCSI HBA
st: Version 20160209, fixed bufsize 32768, s/g segs 256
pcnet32: pcnet32.c:v1.35 21.Apr.2008 tsbogend@alpha.franken.de
e100: Intel(R) PRO/100 Network Driver, 3.5.24-k2-NAPI
e100: Copyright(c) 1999-2006 Intel Corporation
e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
e1000: Copyright (c) 1999-2006 Intel Corporation.
e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-pci: EHCI PCI platform driver
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
ohci-pci: OHCI PCI platform driver
mousedev: PS/2 mouse device common for all mice
i2c /dev entries driver
md: linear personality registered for level -1
md: raid0 personality registered for level 0
md: raid1 personality registered for level 1
device-mapper: uevent: version 1.0.3
device-mapper: ioctl: 4.34.0-ioctl (2015-10-28) initialised: dm-devel@redhat.com
pseries_idle_driver registered
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
oprofile: using timer interrupt.
ipip: IPv4 over IPv4 tunneling driver
NET: Registered protocol family 17
9pnet: Installing 9P2000 support
rtas_msi: calc quota for 0000:00:00.0, request 2
rtas_msi: found prop on dn /pci@800000020000000
rtas_msi: found PE /pci@800000020000000
rtas_msi: counting /pci@800000020000000/unknown-legacy-device@0
rtas_msi: counting /pci@800000020000000/communication-controller@2
rtas_msi: counting /pci@800000020000000/scsi@3
rtas_msi: calc quota for 0000:00:00.0, request 2
rtas_msi: found prop on dn /pci@800000020000000
rtas_msi: found PE /pci@800000020000000
rtas_msi: counting /pci@800000020000000/unknown-legacy-device@0
rtas_msi: counting /pci@800000020000000/communication-controller@2
rtas_msi: counting /pci@800000020000000/scsi@3
rtas_msi: ibm,change_msi(func=4,num=2), got 2 rc = 2
virtio-pci 0000:00:00.0: rtas_msi: allocated virq 29
virtio-pci 0000:00:00.0: rtas_msi: allocated virq 30
Key type dns_resolver registered
Running code patching self-tests ...
Running feature fixup self-tests ...
Running MSI bitmap self-tests ...
registered taskstats version 1
console [netcon0] enabled
netconsole: network logging started
hctosys: unable to open rtc device (rtc0)
Freeing unused kernel memory: 2528K (c000000000c08000 - c000000000e80000)
This architecture does not have kernel memory protection.
create directory /sys
create directory /proc
uptime 0.11 2910930.73

create directory /dev/pts
open hyper channel /dev/vport1p1
send ready message
hyper send type 8, len 0
channel sh.hyper.channel.1, directory sh.hyper.channel.0

open hyper channel /dev/vport1p2
hyper_init_event hyper channel event 0x10025dc0, ops 0x100258f0, fd 3
hyper_add_event add event fd 3, 0x100258f0
hyper_init_event hyper ttyfd event 0x10025d88, ops 0x10025920, fd 4
hyper_add_event add event fd 4, 0x10025920
hyper_loop epoll_wait 1
hyper_handle_event get event 1, de 0x10025dc0, fd 3. ops 0x100258f0
hyper_handle_event event EPOLLIN, de 0x10025dc0, fd 3, 0x100258f0
hyper_event_read
already read 8 bytes data
hyper send type 14, len 4
get length 67
read 59 bytes data, total data 67
hyper send type 14, len 4
0 0 0 1 0 0 0 43 7b 22 68 6f 73 74 6e 61 6d 65 22 3a 22 73 68 65 6c 6c 22 2c 22 63 6f 6e 74 61 69 6e 65 72 73 22 3a 5b 5d 2c 22 73 68 61 72 65 44 69 72 22 3a 22 73 68 61 72 65 5f 64 69 72 22 7d 
 hyper_channel_handle, type 1, len 67
call hyper_start_pod, json {"hostname":"shell","containers":[],"shareDir":"share_dir"}., len 59
call hyper_start_pod, json {"hostname":"shell","containers":[],"shareDir":"share_dir"}., len 59
jsmn parse successed, n is 7
token 0, type is 1, size is 3
token 1, type is 3, size is 1
hostname is shell
token 3, type is 3, size is 1
container count 0
token 5, type is 3, size is 1
share tag is share_dir
create directory /tmp
create directory /tmp/hyper
create directory /tmp/hyper/proc
pci_dma_bus_setup_pSeriesLP: setting up bus /pci@800000020000000
  parent is /pci@800000020000000, iommu_table: 0xc00000000e030c00
finish rescan
create directory /tmp/hyper/shared
pod init pid 324
hyper send type 8, len 0
uptime 9.11 2910939.72

hyper send type 9, len 0
hyper_loop epoll_wait 1
hyper_handle_event get event 1, de 0x10025dc0, fd 3. ops 0x100258f0
hyper_handle_event event EPOLLIN, de 0x10025dc0, fd 3, 0x100258f0
hyper_event_read
already read 8 bytes data
hyper send type 14, len 4
get length 409
read 401 bytes data, total data 409
hyper send type 14, len 4
0 0 0 11 0 0 1 99 7b 22 69 64 22 3a 22 38 64 37 31 65 33 33 38 30 62 64 35 62 33 35 37 61 37 37 66 34 63 39 63 34 31 64 66 30 37 30 38 61 65 35 32 33 38 32 64 33 35 30 61 38 64 39 61 39 33 36 61 63 32 64 32 32 66 66 36 65 31 36 66 22 2c 22 72 6f 6f 74 66 73 22 3a 22 72 6f 6f 74 66 73 22 2c 22 69 6d 61 67 65 22 3a 22 38 64 37 31 65 33 33 38 30 62 64 35 62 33 35 37 61 37 37 66 34 63 39 63 34 31 64 66 30 37 30 38 61 65 35 32 33 38 32 64 33 35 30 61 38 64 39 61 39 33 36 61 63 32 64 32 32 66 66 36 65 31 36 66 22 2c 22 70 72 6f 63 65 73 73 22 3a 7b 22 74 65 72 6d 69 6e 61 6c 22 3a 74 72 75 65 2c 22 73 74 64 69 6f 22 3a 31 2c 22 61 72 67 73 22 3a 5b 22 73 68 22 5d 2c 22 65 6e 76 73 22 3a 5b 7b 22 65 6e 76 22 3a 22 50 41 54 48 22 2c 22 76 61 6c 75 65 22 3a 22 2f 75 73 72 2f 6c 6f 63 61 6c 2f 73 62 69 6e 3a 2f 75 73 72 2f 6c 6f 63 61 6c 2f 62 69 6e 3a 2f 75 73 72 2f 73 62 69 6e 3a 2f 75 73 72 2f 62 69 6e 3a 2f 73 62 69 6e 3a 2f 62 69 6e 22 7d 2c 7b 22 65 6e 76 22 3a 22 54 45 52 4d 22 2c 22 76 61 6c 75 65 22 3a 22 78 74 65 72 6d 22 7d 5d 2c 22 77 6f 72 6b 64 69 72 22 3a 22 2f 22 7d 2c 22 72 65 73 74 61 72 74 50 6f 6c 69 63 79 22 3a 22 6e 65 76 65 72 22 2c 22 69 6e 69 74 69 61 6c 69 7a 65 22 3a 66 61 6c 73 65 7d 
 hyper_channel_handle, type 17, len 409
call hyper_new_container, json {"id":"8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f","rootfs":"rootfs","image":"8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f","process":{"terminal":true,"stdio":1,"args":["sh"],"envs":[{"env":"PATH","value":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},{"env":"TERM","value":"xterm"}],"workdir":"/"},"restartPolicy":"never","initialize":false}, len 401
next container 6
1 name id
container id 8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f
3 name rootfs
container rootfs rootfs
5 name image
container image 8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f
7 name process
1 name terminal
container uses terminal
3 name stdio
container seq 1
5 name args
container init arg 0 sh
8 name envs
envs num 2
envs 0 env PATH
envs 0 value /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
envs 1 env TERM
envs 1 value xterm
20 name workdir
container workdir /
30 name restartPolicy
restart policy never
32 name initialize
create directory /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f
create directory /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/devpts
create directory /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/devpts/
get pty device for exec /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/devpts//0
hyper_setup_exec_tty pts event 0x100311dc338, fd 11 12
hyper_init_event container pts event 0x100311dc338, ops 0x10025950, fd 11
hyper_add_event add event fd 11, 0x10025950
hyper_add_event add event fd 13, 0x10025980
hyper_add_event add event fd 14, 0x100259b0
hyper_container_init in
path /sys/class/scsi_host/host0/scan
bioset (337) used greatest stack depth: 13200 bytes left
finish scan scsi
create directory /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/root
create directory /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/root/
container root directory /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/root/
src directory /tmp/hyper/shared/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/
root directory for container is /tmp/hyper/8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f/root//rootfs, init task sh
create directory ./dev/shm
no dns configured
hyper_dup_exec_tty
hyper send type 8, len 0
container 8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f,init pid 326,ref 4
hyper send type 8, len 0
init (325) used greatest stack depth: 12960 bytes left
hyper send type 9, len 0
hyper_loop epoll_wait 1
hyper_handle_event get event 4, de 0x100311dc338, fd 11. ops 0x10025950
hyper_handle_event event EPOLLOUT, de 0x100311dc338, fd 11, 0x10025950
write_to_stdin, seq 1
hyper_modify_event modify event fd 11, 0x100311dc338, event 1
hyper_loop epoll_wait 3
hyper_handle_event get event 1, de 0x100311dc3a8, fd 14. ops 0x100259b0
hyper_handle_event event EPOLLIN, de 0x100311dc3a8, fd 14, 0x100259b0
stderr_loop, seq 0
pts_loop: read 58 data
pts_loop: read -1 data
hyper_modify_event modify event fd 4, 0x10025d88, event 5
hyper_handle_event get event 1, de 0x100311dc370, fd 13. ops 0x10025980
hyper_handle_event event EPOLLIN, de 0x100311dc370, fd 13, 0x10025980
stdout_loop, seq 1
pts_loop: read -1 data
hyper_handle_event get event 1, de 0x100311dc338, fd 11. ops 0x10025950
hyper_loop epoll_wait 1
hyper_handle_event get event 4, de 0x10025d88, fd 4. ops 0x10025920
hyper_handle_event event EPOLLOUT, de 0x10025d88, fd 4, 0x10025920
hyper_modify_event modify event fd 4, 0x10025d88, event 1
init (326) used greatest stack depth: 10992 bytes left
pid 326 exit normally, status 255
exec pid 326, pid 326
hyper_handle_exec_exit exec exit pid 326, seq 1, container 8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f
still have 3 user of exec
hyper_loop epoll_wait -1
hyper_loop epoll_wait 3
hyper_handle_event get event 16, de 0x100311dc3a8, fd 14. ops 0x100259b0
hyper_handle_event event EPOLLHUP, de 0x100311dc3a8, fd 14, 0x100259b0
stderr_hup
pts_hup, seq 1
still have 2 user of exec
hyper_handle_event get event 16, de 0x100311dc370, fd 13. ops 0x10025980
hyper_handle_event event EPOLLHUP, de 0x100311dc370, fd 13, 0x10025980
stdout_hup
pts_hup, seq 1
still have 1 user of exec
hyper_handle_event get event 16, de 0x100311dc338, fd 11. ops 0x10025950
hyper_handle_event event EPOLLHUP, de 0x100311dc338, fd 11, 0x10025950
stdin_hup
pts_hup, seq 1
last user of exec exit, release
hyper_modify_event modify event fd 4, 0x10025d88, event 5
hyper_release_exec exit code 255
hyper_release_exec container init exited, type 17, remains 1, policy 0
hyper send type 13, len 4
fopen /proc/324/status
find sigign 	0000000000000000
mask is 0
open /tmp/hyper/resolv.conf failed: No such file or directory
hyper_loop epoll_wait 1
hyper_handle_event get event 4, de 0x10025d88, fd 4. ops 0x10025920
hyper_handle_event event EPOLLOUT, de 0x10025d88, fd 4, 0x10025920
hyper_modify_event modify event fd 4, 0x10025d88, event 1
hyper_loop epoll_wait 1
hyper_handle_event get event 1, de 0x10025dc0, fd 3. ops 0x100258f0
hyper_handle_event event EPOLLIN, de 0x10025dc0, fd 3, 0x100258f0
hyper_event_read
already read 8 bytes data
hyper send type 14, len 4
get length 39
read 31 bytes data, total data 39
hyper send type 14, len 4
0 0 0 b 0 0 0 27 7b 22 63 6f 6c 75 6d 6e 22 3a 31 36 39 2c 22 72 6f 77 22 3a 34 37 2c 22 73 65 71 22 3a 31 7d 
 hyper_channel_handle, type 11, len 39
call hyper_win_size, json {"column":169,"row":47,"seq":1}41df0708ae52382d350a8d9a936ac2d22ff6e16f","rootfs":"rootfs","image":"8d71e3380bd5b357a77f4c9c41df0708ae52382d350a8d9a936ac2d22ff6e16f","process":{"terminal":true,"stdio":1,"args":["sh"],"envs":[{"env":"PATH","value":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},{"env":"TERM","value":"xterm"}],"workdir":"/"},"restartPolicy":"never","initialize":false}, len 31
can not find exec whose seq is 1
hyper send type 9, len 0
hyper_loop epoll_wait 1
hyper_handle_event get event 1, de 0x10025dc0, fd 3. ops 0x100258f0
hyper_handle_event event EPOLLIN, de 0x10025dc0, fd 3, 0x100258f0
hyper_event_read
already read 8 bytes data
hyper send type 14, len 4
get length 8
0 0 0 4 0 0 0 8 
 hyper_channel_handle, type 4, len 8
get DESTROYPOD message
hyper send type 9, len 0
reboot: Power down
RTAS power-off r

**Comment by abdasgupta** [comment]
I am attaching the log that is generated from inside the VM after it is spawned by qemu:

[console.txt](https://github.com/hyperhq/runv/files/213141/console.txt)

**Comment by gao-feng** [comment]
@abdasgupta can you show me your open container bundle? for example
```
[root@think-donkey busybox]# tree
.
├── config.json
├── initrd.img
├── process.json
├── rootfs
│   ├── bin
│   │   ├── [
```

**Comment by bpradipt** [comment]
@gao-feng this was indeed a problem with the rootfs. We have been able to successfully run runv on PowerPC
