### ISSUE TITLE
Godep can't restore libvirt, commit 057f70a36a6b5d4ea19be345c2369e27dd022e01 doesnt exit

### ISSUE THREAD

**Issue by WeiZhang555** [hyperhq/runv#171]
https://github.com/hyperhq/runv/blob/master/Godeps/Godeps.json#L11-L13

Godep can't restore libvirt, because this commit 057f70a36a6b5d4ea19be345c2369e27dd022e01  doesnt exist at all.

Can you check it?

**Comment by WeiZhang555** [comment]
Also `github.com/docker/docker` commit d2e7ba42b10fda5961470adc4ba4d74011203e60
doesnt include directory `pkg/term/winconsole` which is used by `runv/lib/term/term_windows.go`

**Comment by feiskyer** [comment]
@WeiZhang555 y, there is a little problem about libvirt Godep, I will update it later

**Comment by feiskyer** [comment]
@WeiZhang555 Got merged.

**Comment by WeiZhang555** [comment]
Nice job, thank you!
