### ISSUE TITLE
Networking for runv VMs

### ISSUE THREAD

**Issue by bpradipt** [hyperhq/runv#185]
Is there any documentation which describes how to setup networking for runv VMs?

**Comment by gao-feng** [comment]
Hust like runc, runv doesn't setup networking itself, it needs a hook program to setup netowrking, this hook program in container-based oci runtime can be  `ip` tool. but for runv, it's a little complicated, we need to create a tap device and use `qmp` to send this tap device to vm. 

Right now this work is on our schedule, hope the information above is helpful for you.

**Comment by bpradipt** [comment]
@gao-feng thanks. This was helpful. I was able to manually configure network in the runv VM
