### ISSUE TITLE
runv-containerd not working on Ubuntu or Fedora

### ISSUE THREAD

**Issue by bpradipt** [hyperhq/runv#200]
Unfortunately spawning a VM via runv-containerd doesn't seem to work. I tried both on Ubuntu and Fedora.
It fails to initialize QMP

4986 qmp_handler.go:181] get qmp welcome failed:

Here are the debug logs - http://pastebin.com/UHsXLpis

**Comment by laijs** [comment]
the qemu stderr is disabled in the code, you can just enable it by editing
https://github.com/hyperhq/runv/blob/master/lib/utils/daemon.go#L74-L77

could you give me the command line you started the runv-containerd?
if you test it with docker, you need to disable the container network by `docker run --net=none`

**Comment by laijs** [comment]
what will happen when the driver is libvirt?
`./runv-containerd --driver libvirt --kernel /root/work/hyperstart/build/kernel --initrd /root/work/hyperstart/build/hyper-initrd.img --debug`

**Comment by bpradipt** [comment]
Here is the debug log with libvirt driver - http://pastebin.com/28v73WrV

This is how I'm running containerd 
qemu driver - ./runv-containerd --kernel /containers/kernel --initrd /containers/hyper-initrd.img --debug
libvirt driver  - ./runv-containerd --driver libvirt --kernel /containers/kernel --initrd /containers/hyper-initrd.img --debug

**Comment by laijs** [comment]
the following lines need to be added into /etc/libvirt/qemu.conf
user = "root"
group = "root"
clear_emulator_capabilities = 0

**Comment by bpradipt** [comment]
The guest kernel is panicking. Here is the log after enabling stderr -
http://pastebin.com/xcYftLzJ

**Comment by laijs** [comment]
does the hyperd works with the /containers/kernel /containers/hyper-initrd.img

**Comment by bpradipt** [comment]
This is a new setup where I took the kernel and initrd from upstream hyperstart. I haven't tried hyperd on this setup.. Will give it a try and update the results. Will also try with a different guest kernel to see if it's a kernel config issue.

**Comment by laijs** [comment]
it seems the rootfs is set readonly. the current hyperstart creates the /lib/modules in the rootfs for bind-mounts for the kernel modules

**Comment by bpradipt** [comment]
The 'rootfs' is not readonly. I'm able to get this working with old hyper-initrd.img. The new one is failing to do bind mount of modules and crashing. Will do more investigation and update

**Comment by laijs** [comment]
but it failed to create the dir ./lib, so I thought the rootfs might be readonly.
I can reproduce your problem by set the rootfs readonly in the config.json.
you are right, more investigation is needed, thanks.

**Comment by bpradipt** [comment]
@laijs, you were right..the issue was due to 'readonly' being set to 'true' and got exposed when using the new initrd with modules support.  Thanks for all your help..
