### ISSUE TITLE
bug report: stdin/stdout hangs when call runv-containerd

### ISSUE THREAD

**Issue by WeiZhang555** [hyperhq/runv#210]
When I try to call runv-containerd with docker, if I don't specify terminal(-t), it hangs.

Normal case with `-t`:
```
$ docker run -ti --net none busybox ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
$
```

it hangs if without `-t`:
```
$ docker run -i --net none busybox ls
bin
dev
etc
home
proc
root
sys
tmp
usr
var

<hangs...Ctrl-C, Ctrl-D don't help>
```

**Comment by laijs** [comment]
runv-containerd had  already reported the exit event and closed all the stdio fifo. (I don't know what is missing).
the docker daemon still hold the stdin fifo with rw access. so the docker attach can't end.
