### ISSUE TITLE
Integrate runV with Docker

### ISSUE THREAD

**Issue by gnawux** [hyperhq/runv#23]
Docker is going to modify the Engine to directly call a binary implementing the Open Containers Specification, such as runC, rather than relying on an execution driver calling an external library (libcontainer) to set the container runtime up [1].
runV being the hypervisor-based equivalent of runC, it should be able to integrate with Docker.

However, several aspects require attention to perform a successful integration:
1. Fit runV Pod model to Docker’s single container model;
2. Make runV networking compatible with Docker’s CNM model;
3. Properly configure virtual machines with OCI specifications;
4. Implement all Docker runtime operations.
## Model: Pod (or group of containers)

runV is designed to not only run one app-centric container within a VM, but instead run groups of containers related together (Pod); leveraging the VM as the hard boundaries of that Pod. It helps to optimise the VM density by reducing the memory overhead of the guest kernel and the hypervisor process, and also makes it easy to share namespaces among containers.

There is a pattern for container based apps, which consists in tight coupled containers as a scheduling unit. This pattern is implemented by Kubernetes Pod, among others.

However, Pods are not in Docker’s current model, i.e. it is not possible to create a Pod with Docker/runC. To have the Pod concept in Docker’s model, runV will treat each VM as an element equivalent to the network namespace, i.e:
- in containers’ world, a Pod could be created in a single network namespace
- in hypervisors’ world, a Pod could be created in a single VM
## Containers Networking

runV’s networking part is going to fit the libnetwork CNM model:
- Network: Bridge or OVS or others
- Endpoint: The address and route info
- Sandbox: The virtual machine, instead of a network namespace

The endpoint will “join” the Sandbox (using the method `endpoint.Join(sandbox)`) after a VM boots, and before the container starts to run. This will be implemented using the `pre-start` hook present in the OCI specs. As a VM is different than a container, runV will provide a new libnetwork driver, as well as a specific net hook program to setup the network of the hypervisor.
## Configure virtual machines with OCI specifications

Currently, runV can launch VMs according to OCI specs, equivalent to runC. It is not yet optimized, and runV shall introduce some extra configuration parameters.
### VM Boot parameter customization

runV is based on hypervisor technology, thus it requires path to `kernel` and `initrd` files to run containers with Kvm/Xen hypervisors; and path to `vbox-boot-iso` file in VirtualBox hypervisor. We suggest to add these values to the runtime configuration, i.e:

```
{
    "kernel": "/var/lib/hyper/vmlinuz",
    "initrd": "/var/lib/hyper/hyper-initrd.gz"
}
```
### Configure vCPU number

Hypervisors require the number of vCPUs to be set to run a container in a VM.
Although runV can get the number of vCPUs from `Resources.CPU.Cpus`, the original purpose of this value is to be used for CPU affinity, and usually represents all the CPUs of the host by default. As it is too expensive for runV to use all the CPUs to run a container, runV needs a dedicated vCPU configuration entry.
### Block device as rootfs

runV can run with a host directory as rootfs, which relies on features of hypervisors, such as virtfs (9p) for Kvm/Xen, or vboxsf for VirtualBox. These features work but cannot provide performances comparable to a native filesystem. It is better for runV to run on a hypervisor volume (image).

It would be better if the rootfs is allowed to be configured through the `mount` entry in the `runtime.json` file. Mount supports block devices, directories, and pseudo filesystems (procfs, sysfs, ...); then, runV could setup a raw device, or a hypervisor disk image, as rootfs.
### Configure volumes (disk image) formats in specs

For mounting disk images as volumes, such as `qcow2`, `rbd`, or `vdi` formats, it is better to define these formats in the configuration, i.e:

```
"data": {
    "type": "xfs",
    "source": "qcow2:/volumes/testing.qcow",
    "options": ["noatime","noexec"]
}
```
### tty

runV will provide tty/terminal access, as runC does.
### exec

For runC containers, `runc exec` can execute programs in runC containers through `setns` and the `namespace path`. However, runV containers are running as VMs, which means `setns` and `namespace path` are meaningless for `runv exec`. `runv exec` needs a specific channel to notify the VM to execute programs. runV currently setups the channels based on a serial port device of the VM. These channels should be stored in a container’s state, then multiple `runv exec` can use the same channel to access the same VM.
### pause/unpause and migration

The pause/unpause and migration in runV will be implemented in the context of the hypervisor.

[1] [Docker Roadmap](https://github.com/docker/docker/blob/bf892dcfcc002ee374057033a940ce2250181066/ROADMAP.md)

**Comment by gurvindersingh** [comment]
I think it would be good/better fit to make it compatible with kubernetes to give option to run docker/rkt container or container run in vm using runv. It will add real value in terms of security and might enable running windows in linux container (i am lacking knowledge as if runv can run windows or not)

**Comment by jamesodhunt** [comment]
Regarding "VM Boot parameter customization", see docker/docker#21324.

**Comment by gao-feng** [comment]
spit create and start container, https://github.com/opencontainers/runtime-spec/pull/384

**Comment by wrouesnel** [comment]
Regarding vCPU numbers: wouldn't cpushare be available? Presumably a hypervisor with access to CPUs but share limited could avoid the resource overhead?
