### ISSUE TITLE
use virtio-vsock to communicate with hyperstart

### ISSUE THREAD

**Issue by bergwolf** [hyperhq/runv#278]
virtio-vsock (http://qemu-project.org/Features/VirtioVsock) was introduced as a communication device between host and guest. runv and hyperstart can use it to replace current serial port communication method.

**Comment by feiskyer** [comment]
@bergwolf Which version of qemu supports this?

**Comment by bergwolf** [comment]
@feiskyer none... It only exists in Stephan's qemu repo (https://github.com/stefanha/qemu/tree/vsock), and corresponding kernel support is still under development (got merged on Dec 3, 2015 https://github.com/torvalds/linux/commit/c402293bd76fbc93e52ef8c0947ab81eea3ae019 and reverted on Dec 9, 2015 https://github.com/torvalds/linux/commit/8ac2837c89c8c0fcad557e4380aeef80580390f9)

Maybe we should reconsider it later when the code gets more stability.

**Comment by bergwolf** [comment]
The delay was due to a missing feature that virtio-vsock needs to allow only host to make the connection. See https://lists.linuxfoundation.org/pipermail/virtualization/2015-December/030913.html

**Comment by bergwolf** [comment]
close via https://github.com/hyperhq/runv/pull/411
