### ISSUE TITLE
yum isn't working inside vm

### ISSUE THREAD

**Issue by wcwxyz** [hyperhq/runv#288]
I'm trying docker + runv-containerd + runv with stock kernel/initrd from hyperstart project.
After I run:
`docker run -it --rm centos:6 /bin/bash`

Inside the vm:

```
[root@4a2b5ba9b6ef /]# yum
rpmdb: mmap: Invalid argument
error: db3 error(22) from dbenv->open: Invalid argument
error: cannot open Packages index using db3 - Invalid argument (22)
error: cannot open Packages database in /var/lib/rpm
CRITICAL:yum.main:

Error: rpmdb open failed
```

**Comment by wcwxyz** [comment]
I tested with centos:7, yum/rpm is working fine.

**Comment by crook** [comment]
@wcwxyz  can you show the output of the following comand?

yum --debuglevel=3 clean all
yum --debuglevel=3 makecache

**Comment by wcwxyz** [comment]
It seems like a 9p filesystem issue. After I modified hypertstart to mount 9p fs with "trans=virtio,cache=mmap", it works.

**Comment by gnawux** [comment]
related with hyperhq/hyperstart#88

**Comment by bergwolf** [comment]
This `rpmdb open failed` error is fixed with https://github.com/hyperhq/hyperstart/issues/74

The remaining yum `Rpmdb checksum is invalid` issue is tracked in hyperhq/hyperstart#88. So close this one.
