### ISSUE TITLE
init_comm: should we reply all commands in queue when got INIT_FINISHPOD messsage?

### ISSUE THREAD

**Issue by gnawux** [hyperhq/runv#317]
here: https://github.com/hyperhq/runv/blob/master/hypervisor/init_comm.go#L263

Image such a case:
1. Client initiate a Kill command to the last container, which will lead to the container exit and pod finish.
2. Before the container is killed (before `INIT_FINISHPOD` was received by runV), Client initiate a second kill command.
3. Before the second command was replied by hyperstart, the init_comm got `INIT_FINISHPOD`

Then the second kill  command will never got replied.

**Comment by laijs** [comment]
yes, we should

**Comment by laijs** [comment]
I think it was fixed in this case. And https://github.com/hyperhq/runv/pull/447 ensure all the commands will be replied in all cases.
