### ISSUE TITLE
convert containerd in runv to a new supervisord

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/runv#380]
(1) Now we use containerd as the supervisor of runv. Howerver the API of containerd is coupling serious with dockerd and runc, depending on it as supervisor may unreasonable.And it will be hard to extend the API of runv because of the constraint of the API of containerd.
(2) So in order to make runv more scalable,we use supervisord to replace containerd. For now, we only rename everything relevant with containerd to supervisord in runv. And extract the definition the API of containerd from dependency to be our supervisord's API.Therefore we can extend the API of supervisord as needed and won't be restricted by the API of containerd anymore.

**Comment by gnawux** [comment]
could we close this issue @YaoZengzeng ？

**Comment by laijs** [comment]
close it since #537 is merged.
