### ISSUE TITLE
hyperstart

### ISSUE THREAD

**Issue by laijs** [hyperhq/runv#415]
- [x] **libhyperstart**: move hyperstart code in runv/hypervisor to runv/hyperstart/libhyperstart (serial-json-protocol)
- [x] **pb-spec**: add pb protocol for tcp/unix/vsock (socket-pb-protocol)
- [x] **go-server**: implement simple server for socket-pb-protocol
- [ ] **go-client**: implement libhyperstart.Hyperstart based on socket-pb-protocol
- [x] **proxy**: add proxy to translate socket-pb-protocol to serial-json-protocol. 
         ( go-client --pb-spec--> go-server --json-spec--> hyperstart)
- [x] **oci**: refactor runv-cli. based on file-lock for vm management, and talk to serial-hyperstart via proxy or directly talk to vsock-hyperstart (next item)
- [x] **hyperstart-pb-server**: implement socket-pb-protocol server in hyperstart (for vsock, or tcp, or ssh (via tcp+port-forwarding))
- [x] simplify libhyperstart.Hyperstart and libhyperstart

**Comment by sameo** [comment]
@laijs Have you considered re-using our [Clear Containers proxy](https://github.com/01org/cc-oci-runtime/tree/master/proxy) implementation ? It would be a shame to duplicate code here if we're essentially looking at doing the same thing.
Also, we're planning to move the Clear Containers proxy as [a standalone component](https://lists.01.org/pipermail/cc-devel/2017-January/000020.html). We're definitely ready to extend the proxy implementation to support your requirements.

**Comment by laijs** [comment]
@sameo but I am planning to define the **same** spec for the proxy and for the hyperstart-pb-server. it is important for moving serial from vsocks
we can't use the Clear Containers proxy if the specs for cc-proxy is different than ours.

**Comment by gnawux** [comment]
How about setup a repo maintained by both cc and runv team? If we could have an org for virtualized container, I think we could donate hyperstart to it as well.

**Comment by sameo** [comment]
@gnawux @laijs Would github.com/clearcontainers be a good place for that ?

**Comment by sameo** [comment]
@laijs Do you have the hyperstart-pb-server spec defined somewhere ?

**Comment by sameo** [comment]
@laijs Also, will the hyperstart-pb-server protocol be used over the serial port as well ?

**Comment by gnawux** [comment]
@laijs what's the current status of this issue?
