### ISSUE TITLE
panic due to delay version-awared command

### ISSUE THREAD

**Issue by gao-feng** [hyperhq/runv#429]
http://ci.hyper.sh:8080/job/hyperstart-auto/37/console

04:38:59 I0121 04:38:58.222888    5619 serial.go:233] delay version-awared command :6
04:38:59 E0121 04:38:58.223047    5619 hypervisor.go:43] SB[vm-KoptECacOK] watch hyperstart timeout
04:38:59 I0121 04:38:58.223061    5619 serial.go:65] close serialBasedHyperstart
04:38:59 I0121 04:38:58.223085    5619 serial.go:362] tty chan closed, quit sent goroutine
04:38:59 E0121 04:38:58.223126    5619 serial.go:337] read tty data failed
04:38:59 I0121 04:38:58.223142    5619 serial.go:394] tty socket closed, quit the reading goroutine read unix @->/var/run/hyper/vm-KoptECacOK/tty.sock: use of closed network connection
04:38:59 I0121 04:38:58.223151    5619 hypervisor.go:23] vm vm-KoptECacOK: main event loop got message 16(ERROR_INIT_FAIL)
04:38:59 E0121 04:38:58.223160    5619 vm_states.go:232] SB[vm-KoptECacOK] watch hyperstart timeout
04:38:59 E0121 04:38:58.223165    5619 vm_states.go:177] Shutting down because of an exception: connection to vm broken
04:38:59 I0121 04:38:58.223171    5619 vm_states.go:180] SB[vm-KoptECacOK] poweroff vm based on command: connection to vm broken
04:38:59 I0121 04:38:58.223180    5619 context.go:219] SB[vm-KoptECacOK] VmContext Close()
04:38:59 I0121 04:38:58.223216    5619 qemu_process.go:91] kill Qemu... 6244
04:38:59 I0121 04:38:58.223257    5619 serial.go:198] vm channel closed, quit
04:38:59 E0121 04:38:58.223280    5619 networks.go:85] Pod[service] Nic[eth-default] failed to add NIC: hyperstart closed
04:38:59 E0121 04:38:58.223310    5619 serial.go:111] read init data failed
04:38:59 I0121 04:38:58.223332    5619 serial.go:519] get hyperstart API version error: hyperstart closed
04:38:59 I0121 04:38:58.223340    5619 serial.go:519] get hyperstart API version error: hyperstart closed
04:38:59 I0121 04:38:58.223344    5619 serial.go:158] hyperstart API version:4243, VM hyperstart API version: 0
04:38:59 panic: send on closed channel
04:38:59 
04:38:59 goroutine 13474 [running]:
04:38:59 panic(0x11a11c0, 0xc420c95f70)
04:38:59 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
04:38:59 github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hyperstart/libhyperstart.handleMsgToHyperstart.func1()
04:38:59 	/home/jenkins/workspace/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/serial.go:235 +0x4d

**Comment by laijs** [comment]
fixed by #482
