### ISSUE TITLE
Error detected when start a runv container

### ISSUE THREAD

**Issue by WeiZhang555** [hyperhq/runv#450]
This is the message I got when I'm starting a runv container:

![image](https://cloud.githubusercontent.com/assets/1203611/23853846/75d32c5c-0829-11e7-822e-db0fbd8a50a8.png)

This is not a "always" error, but it happens quite frequently.

**Comment by WeiZhang555** [comment]
After research, I found root cause of this problem is that when the client call `monitorTtySize`, the `init` process hasn't started at that time, I got the error from debug message:

```
call hyper_set_win_size, can not find the process: init
```

**Comment by gnawux** [comment]
@WeiZhang555 does this bug still exist?

**Comment by WeiZhang555** [comment]
It never left us... :rofl:

**Comment by laijs** [comment]
this message was definite removed after cli-refactor. monitorTtySize is only called when container is started.
