### ISSUE TITLE
testing fails randomly

### ISSUE THREAD

**Issue by dvoytik** [hyperhq/runv#458]
You might noticed that the same code randomly passes or fails testing.
Even on github you can see this:
This one failed: https://travis-ci.org/hyperhq/runv/builds/211187580
and next commit passes: https://travis-ci.org/hyperhq/runv/builds/213013508
and the difference between these two: d7530ca44354e46dc56918d76544e668740ef32d

**Comment by gnawux** [comment]
the random failures were tracked in, hyperhq/hyperd#557, hyperhq/hyperd#601, hyperhq/hyperd#603, and hyperhq/hyperd#612. 

And these failures were fixed in v0.8.1
