### ISSUE TITLE
vm factory may return vm=nil, err=nil for GetVm

### ISSUE THREAD

**Issue by gnawux** [hyperhq/runv#499]
This is the root cause of hyperhq/hyperd#612 . The case is covered by hyperhq/hyperd#615, however, it should not return `err=nil` in a failed case.

**Comment by laijs** [comment]
it  is found after careful review...

**Comment by gnawux** [comment]
fixed by #504

**Comment by laijs** [comment]
#504 is unrelated for the problem.

**Comment by gnawux** [comment]
but looks really like this case
