### ISSUE TITLE
Failed to create container

### ISSUE THREAD

**Issue by seafooler** [hyperhq/runv#522]
I have encountered an error when run `runv` as the [document](https://github.com/hyperhq/runv) guides.
When I input the command below to create a new runv:
```
sudo runv --kernel kernel --initrd hyper-initrd.img --driver qemu create test
```
The output error shows:
```
Run Container error: failed to create container: rpc error: code = Unknown desc = StartPod fail
```
Any comments and suggestions will be appreciated.

**Comment by laijs** [comment]
@seafooler  Could you please retry it and provide more information?
The logs of the runv are at: /var/log/hyper. There are multiple log files for each container.
