### ISSUE TITLE
Does runv have a logo?

### ISSUE THREAD

**Issue by dankohn** [hyperhq/runv#542]
Does runv have a logo? We'd like to include it in the next version of https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_v0.9.5_cncf.jpg

Cc @shawnpreissner

**Comment by resouer** [comment]
cc @laijs @gao-feng @gnawux

**Comment by gnawux** [comment]
Thank you @dankohn , we will have one soon

**Comment by gnawux** [comment]
PR #563 got the logo done, and @resouer has submit it in cncf/landscape#144. 

Thank you @dankohn
