### ISSUE TITLE
cpus constraint in runv

### ISSUE THREAD

**Issue by jovizhangwei** [hyperhq/runv#581]
Hi,

I just tried cpu limiting options with runv, it seems runv cannot accept docker options like --cpuset-cpus and --cpus, just want to confirm this constraint. ("docker run -m" is fine)

qemu options
```
-smp cpus=1,maxcpus=8 -numa node,nodeid=0,cpus=0-7,mem=1024
```
Why the cpus is always 1?

If this cpu constraint is right, we should write it down in Doc clearly.

**Comment by bergwolf** [comment]
Fixed by https://github.com/hyperhq/runv/pull/589. `--cpus` is rounded up to specify guest CPU number.
