### ISSUE TITLE
runv could not work properly with kvmtool on arm platform with gicv2

### ISSUE THREAD

**Issue by Weichen81** [hyperhq/runv#622]
kvmtool supports 3 kinds of virtual irqchip for arm platforms: gicv2, gicv3 and
gicv3-its. But these 3 kinds of virtual irqchip must have correct real irqchip
to support them. In current code, we fix the irqchip to gicv3. This may work fine
for those systems that are using gicv3 or gicv4. But on a system with gicv2 or gicv2m,
the kvmtool could not start properly.

We have create a PR# https://github.com/hyperhq/runv/pull/621 to fix this issue.

**Comment by gao-feng** [comment]
Pr merged, thanks!
