### ISSUE TITLE
Do we have a plan to release some binary of runV?

### ISSUE THREAD

**Issue by allencloud** [hyperhq/runv#623]
Hi, my friends,

I have one request for runv that if there is any possibility for us to release some binary of runv. I think with this way, we can bring a lot of convenience to our users.

We just download a binary and locate in the PATH. How convenient!
Install go and setup env and go get the code and checkout the right version, I don't think this is a good way for users.

Please take this into consideration.

**Comment by houstar** [comment]
I agreed with @allencloud 's request since I'm the new user just want to experience the runv instead runc.

**Comment by laijs** [comment]
duplicated with #574
