### ISSUE TITLE
Support other guest OSs that run VirtualBox

### ISSUE THREAD

**Issue by ghost** [hyperhq/runv#64]
Eg. Windows and FreeBSD.

**Comment by gnawux** [comment]
@herby it's a good suggestion to support more OS, however, virtualbox might not be the best candidate on every platform. We will adopt more hypervisors and support more OSes. And any contributions are welcome as well.

**Comment by herby** [comment]
@gnawux Emm... I really don't know which hypervisor would be the best, and I was not suggesting VirtualBox's one is. My point was, you already have taken this path ("foreign" host OS, using hypervisor from VirtualBox) on OS X, so taking this tried path on Windows and FreeBSD should be possible a lot faster. And then when you can claim you can run on every major OS, it would be much stronger point to use hyper.

Optimizing the experience by choosing the most appropriate one for each OS can be done later.

Or?

**Comment by gurvindersingh** [comment]
Will runv be able to run windows inside created VM or it is limited to linux only. It might be mentioned somewhere but couldn't found it so asking to confirm. 

Between really nice work and loooking forward to see it merged it with upstream k8s and may be other resource managers.

**Comment by gnawux** [comment]
@gurvindersingh current it support linux only, because it launch vm with linux kernel and init

**Comment by gurvindersingh** [comment]
Ok. But is there plan to add support for Windows in near future as Windows
containers are also getting there.

**Comment by gnawux** [comment]
@gurvindersingh no plan yet, but we'd like to learn suggestions.

**Comment by laijs** [comment]
VirtualBox driver was disabled and partially removed
